services:
  backend:
    build:
      context: .
      dockerfile: DockerFile.Backend
    container_name: backend
    env_file:
      - .env
    ports:
      - "5000:5000"
    networks:
      - portfolio-network

  frontend:
    build:
      context: .
      dockerfile: DockerFile.Frontend
    container_name: frontend
    env_file:
      - .env
    ports:
      - "80:80"
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge
