# Base image
FROM node:22-alpine

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY Backend/package*.json ./

# Install dependencies
RUN npm install

# Copy the backend source code
COPY Backend/ ./

# Expose the port
EXPOSE 5000

# Start the server
CMD ["node", "app.js"]
